### PR TITLE
Avoid userconnected to update members and create members directly + Autocomplete error fix + added missing import in setRoom

### LINKED ISSUE #275: Add member update function and fix userConnected
basically, make it so that /modules/sockets/userConnected.mjs DOESNT update the member anymore, and only makes changes on INITIAL account creations. Everything else will need to use the new member update feature internally to avoid bullshit sync issues.

### PR DESCRIPTION
**Pull request by uncleman11**
Fixes #275

### CODE REVIEW

File: modules/functions/member.mjs [hunk 1]
```diff
@@ -0,0 +1,52 @@
+import {serverconfig} from "../../index.mjs";
+import {saveMemberToDB} from "./mysql/helper.mjs";
+import {sanitizeHTML, stripHTML} from "./sanitizing/functions.mjs";
+
+export function createMember(id, token, name, loginName, icon, banner, aboutme, status, country_code, publicKey, joined, lastOnline, hashedPassword, isVerifiedKey, onboarding) {
```
Comment (hackthedev) [inline modules/functions/member.mjs]: What if data is missing

File: modules/functions/member.mjs [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    }
+    if(member?.token !== undefined) serverconfig.servermembers[member?.id].token = member?.token;
+    if(member?.name !== undefined) serverconfig.servermembers[member?.id].name = stripHTML(member?.name);
+    if(member?.loginName !== undefined) serverconfig.servermembers[member?.id].loginName = stripHTML(member?.loginName);
+    if(member?.icon !== undefined) serverconfig.servermembers[member?.id].icon = stripHTML(member?.icon);
+    if(member?.banner !== undefined) serverconfig.servermembers[member?.id].banner = stripHTML(member?.banner);
+    if(member?.aboutme !== undefined) serverconfig.servermembers[member?.id].aboutme = sanitizeHTML(member?.aboutme, false);
+    if(member?.nickname !== undefined) serverconfig.servermembers[member?.id].nickname = stripHTML(member?.nickname);
+    if(member?.status !== undefined) serverconfig.servermembers[member?.id].status = member?.status;
+    if(member?.country_code !== undefined) serverconfig.servermembers[member?.id].country_code = sanitizeHTML(member?.country_code, false);
```
Comment (hackthedev) [inline modules/functions/member.mjs:47]: country_code is server handled

File: modules/functions/member.mjs [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+        throw "Member does not exist and therefore it cannot be updates."
+    }
+    if(member?.token !== undefined) serverconfig.servermembers[member?.id].token = member?.token;
+    if(member?.name !== undefined) serverconfig.servermembers[member?.id].name = stripHTML(member?.name);
+    if(member?.loginName !== undefined) serverconfig.servermembers[member?.id].loginName = stripHTML(member?.loginName);
+    if(member?.icon !== undefined) serverconfig.servermembers[member?.id].icon = stripHTML(member?.icon);
+    if(member?.banner !== undefined) serverconfig.servermembers[member?.id].banner = stripHTML(member?.banner);
+    if(member?.aboutme !== undefined) serverconfig.servermembers[member?.id].aboutme = sanitizeHTML(member?.aboutme, false);
+    if(member?.nickname !== undefined) serverconfig.servermembers[member?.id].nickname = stripHTML(member?.nickname);
+    if(member?.status !== undefined) serverconfig.servermembers[member?.id].status = member?.status;
```
Comment (hackthedev) [inline modules/functions/member.mjs]: missing sanitizing

File: modules/functions/member.mjs [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+
+
+export function updateMember(member) {
+    if(!member?.id) {
+        throw "Member id is missing when updating member."
+    }
+    if (!member?.id in serverconfig.servermembers) {
+        throw "Member does not exist and therefore it cannot be updates."
+    }
+    if(member?.token !== undefined) serverconfig.servermembers[member?.id].token = member?.token;
```
Comment (hackthedev) [inline modules/functions/member.mjs]: we should use stripHtml

File: modules/functions/member.mjs [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+    if(member?.name !== undefined) serverconfig.servermembers[member?.id].name = stripHTML(member?.name);
+    if(member?.loginName !== undefined) serverconfig.servermembers[member?.id].loginName = stripHTML(member?.loginName);
+    if(member?.icon !== undefined) serverconfig.servermembers[member?.id].icon = stripHTML(member?.icon);
+    if(member?.banner !== undefined) serverconfig.servermembers[member?.id].banner = stripHTML(member?.banner);
+    if(member?.aboutme !== undefined) serverconfig.servermembers[member?.id].aboutme = sanitizeHTML(member?.aboutme, false);
+    if(member?.nickname !== undefined) serverconfig.servermembers[member?.id].nickname = stripHTML(member?.nickname);
+    if(member?.status !== undefined) serverconfig.servermembers[member?.id].status = member?.status;
+    if(member?.country_code !== undefined) serverconfig.servermembers[member?.id].country_code = sanitizeHTML(member?.country_code, false);
+    if(member?.publicKey !== undefined) serverconfig.servermembers[member?.id].publicKey = member?.publicKey;
```
Comment (hackthedev) [inline modules/functions/member.mjs]: missing sanitizing

File: modules/functions/member.mjs [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+    if(member?.isVerifiedKey !== undefined) serverconfig.servermembers[member?.id].isVerifiedKey = member?.isVerifiedKey
```
Comment (hackthedev) [inline modules/functions/member.mjs:49]: the other keys come from the server

File: modules/sockets/userConnected.mjs [hunk 7]
```diff
@@ -31,10 +31,11 @@ import {
 import {sendSystemMessage} from "./home/general.mjs";
 import {discoverHosts} from "../functions/discovery.mjs";
 import {isValidProof, powVerifiedUsers} from "./pow.mjs";
-import {saveMemberToDB} from "../functions/mysql/helper.mjs";
 import {checkMemberBan} from "../functions/ban-system/helpers.mjs";
 import {sanitizeHTML, stripHTML} from "../functions/sanitizing/functions.mjs";
 import {autobanXSS} from "../functions/sanitizing/actions.mjs";
+import {createMember} from "../functions/member.mjs";
```
Comment (hackthedev) [inline modules/sockets/userConnected.mjs]: lets do this:
```
import { createMember, updateMember } from "../functions/member.mjs";
```

**Review by hackthedev — CHANGES_REQUESTED** [review]
